#######################################################################################
# Book settings
title                       : "Probabilistic Machine Learning"
copyright                   : "2022"  # Copyright year to be placed in the footer
execute:
  execute_notebooks: false
  
launch_buttons:
  colab_url: "https://colab.research.google.com"

repository:
  url: https://github.com/probml/pyprobml
  branch: master
  
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify 
    - substitution

html:
  use_issues_button         : true  # Whether to add an "open an issue" button
  use_repository_button     : true  # Whether to add a link to your repository button