name: Main workflow

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
    # Clone the reference repository
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Check code formatting of notebooks
      run: |
        pip install black[jupyter]
        black --check --verbose notebooks/book1/*.ipynb
        black --check --verbose notebooks/book2/*.ipynb
    
    - name: Check notebooks for errors
      run: |
        pip install pytest jupyter
        pytest -s --verbose tests/test_notebooks.py