name: Workflow

on:
  push:
    branches:
    - master
    - dashboard2
    
  pull_request:
    branches:
    - master
    
jobs:
  combine_and_publish_results:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
    - name: Clone the reference repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install git+https://github.com/probml/probml-utils.git | cat
        pip install -U --no-cache-dir -r requirements-dev.txt | cat
        pip install -U --no-cache-dir -r requirements.txt | cat

    - name: Combine and publish results
      run: |
        python .github/scripts/combine_results.py --user_name ${{ github.repository }}
        python .github/scripts/create_figure_dashboard.py --user_name ${{ github.repository }}
      
    - name: Push test-results to workflow_testing_indicator (does not run on pull requests)
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: workflow_testing_indicator/
        publish_branch: workflow_testing_indicator
      if: always() && github.event_name == 'push'  # Don't run on pull requests