name: Workflow

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the reference repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.7.12
      uses: actions/setup-python@v2
      with:
        # Change this based on the python version in Google colab
        # actions/setup-python@v2 does not have 3.7.13
        python-version: '3.7.12'

    - name: Install dependencies
      run: |
        pip install black[jupyter]==22.3.0  # Change this based on .pre-commit-config.yaml

    - name: Check code quality
      run: |
        black --check --verbose notebooks/book1/*/*.ipynb
        black --check --verbose notebooks/book2/*/*.ipynb  

  static_import_check:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the reference repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.7.12
      uses: actions/setup-python@v2
      with:
        # Change this based on the python version in Google colab
        # actions/setup-python@v2 does not have 3.7.13
        python-version: '3.7.12'

    - name: Install dependencies
      run: |
        pip install -U --no-cache-dir -r requirements-dev.txt | cat
        pip install -U --no-cache-dir -r requirements.txt | cat

    - name: Check static imports
      run: |
        pytest -n auto -s --verbose tests/test_imports.py

  execute_notebooks:
    runs-on: ubuntu-latest
    # needs: [check_code_quality, static_import_check]
    container: texlive/texlive:TL2020-historic
    steps:
    - name: Clone the reference repository
      uses: actions/checkout@v2
    
    - name: Setup Python 3.7.13 (current colab version)
      shell: bash
      run: |
        curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh --output miniconda.sh
        mkdir /root/.conda
        bash miniconda.sh -b
        rm miniconda.sh
        echo "export PATH=\"\$HOME/miniconda3/bin:\$PATH\"" >> /root/.bashrc
        echo "source \"\$HOME/miniconda3/bin/activate\"" >> /root/.bashrc
        source /root/.bashrc
        conda create -n py37 python=3.7.13 -y
        echo "conda activate py37" >> /root/.bashrc

    - name: Install requirements
      shell: bash
      run: |
        source /root/.bashrc
        pip install -U --no-cache-dir -r requirements-dev.txt | cat
        pip install -U --no-cache-dir -r requirements.txt | cat

    - name: Check code quality (again)
      shell: bash
      run: |
        source /root/.bashrc
        black --check --verbose notebooks/book1/*/*.ipynb
        black --check --verbose notebooks/book2/*/*.ipynb

    - name: Check notebooks for errors
      shell: bash
      run: |
        source /root/.bashrc
        pytest -n auto -s --verbose tests/test_notebooks.py

    - name: Push figures to auto_generated_figures (does not run on pull requests)
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: figures/
        publish_branch: auto_generated_figures
      if: github.event_name == 'push'  # Don't run on pull requests
  
    - name: Push test-results to workflow_testing_indicator (does not run on pull requests)
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: test_results/
        publish_branch: workflow_testing_indicator
      if: always() && github.event_name == 'push'  # Don't run on pull requests
